# rule identifiers turned on by default to exclude from running
disabled_rules:
   - trailing_whitespace
   - force_cast
   - force_unwrapping
   - force_try
   - line_length
   - empty_enum_arguments
   - unused_optional_binding
   - redundant_string_enum_value
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
